language: android

jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  - android list target

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by the project
    - build-tools-24.0.1

    # The SDK version used to compile the project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-23
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-17

script:
  - ./gradlew clean build test